version: '3'

services:
  web:
    build: 
      context: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # Se você quiser criar um usuário regular adicional no MySQL (que não seja o root),
      # você pode descomentar as duas linhas abaixo e definir os valores no arquivo .env.
      # Por exemplo: DB_USER=myuser e DB_USER_PASSWORD=mypassword
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  mysql-data:
